export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const INCLUDE_COUNTER = "INCLUDE_COUNTER"
export const REMOVE_COUNTER = "REMOVE_COUNTER"
export const INC_COUNTER = "INC_COUNTER"
export const DEC_COUNTER = "DEC_COUNTER"
export const RESET_COUNTER = "RESET_COUNTER"